/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import config.Koneksi;
import dao.DAO_Gudang;
import dao.DAO_Laporan;
import service.Service_Laporan;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Administrator
 */
public class Master_Report extends javax.swing.JPanel {

    /**
     * Creates new form Master_Report
     */
    private Service_Laporan servis_lap = new DAO_Laporan();

    
    public Master_Report() {
        initComponents();
        pn_dataBarang.setVisible(false);
        pn_dataLokasi.setVisible(false);
        pn_dataKaryawan.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pn_pilihLaporan = new custom.panelCustom();
        cbx_laporan = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        pn_dataBarang = new custom.panelCustom();
        jLabel3 = new javax.swing.JLabel();
        btn_printbarang = new javax.swing.JButton();
        pn_dataLokasi = new custom.panelCustom();
        jLabel4 = new javax.swing.JLabel();
        btn_printLokasi = new javax.swing.JButton();
        pn_dataKaryawan = new custom.panelCustom();
        jLabel5 = new javax.swing.JLabel();
        btn_printKaryawan = new javax.swing.JButton();
        pn_tampilLaporan = new custom.panelCustom();
        panelCustom3 = new custom.panelCustom();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(35, 39, 47));
        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(35, 39, 47));

        pn_pilihLaporan.setBackground(new java.awt.Color(255, 255, 255));
        pn_pilihLaporan.setRoundBottomLeft(20);
        pn_pilihLaporan.setRoundBottomRight(20);
        pn_pilihLaporan.setRoundTopLeft(20);
        pn_pilihLaporan.setRoundTopRight(20);

        cbx_laporan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "* Pilih Laporan *", "Laporan Data Barang", "Laporan Lokasi", "Laporan Karyawan" }));
        cbx_laporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_laporanActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Pilih Jenis Laporan");

        pn_dataBarang.setBackground(new java.awt.Color(204, 204, 255));
        pn_dataBarang.setRoundBottomLeft(15);
        pn_dataBarang.setRoundBottomRight(15);
        pn_dataBarang.setRoundTopLeft(15);
        pn_dataBarang.setRoundTopRight(15);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Laporan Data Barang");

        btn_printbarang.setBackground(new java.awt.Color(0, 204, 204));
        btn_printbarang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_printbarang.setForeground(new java.awt.Color(255, 255, 255));
        btn_printbarang.setText("Cetak");
        btn_printbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printbarangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_dataBarangLayout = new javax.swing.GroupLayout(pn_dataBarang);
        pn_dataBarang.setLayout(pn_dataBarangLayout);
        pn_dataBarangLayout.setHorizontalGroup(
            pn_dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_dataBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pn_dataBarangLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(btn_printbarang, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        pn_dataBarangLayout.setVerticalGroup(
            pn_dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_dataBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(27, 27, 27)
                .addComponent(btn_printbarang)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pn_dataLokasi.setBackground(new java.awt.Color(204, 204, 255));
        pn_dataLokasi.setRoundBottomLeft(15);
        pn_dataLokasi.setRoundBottomRight(15);
        pn_dataLokasi.setRoundTopLeft(15);
        pn_dataLokasi.setRoundTopRight(15);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Laporan Data Lokasi");

        btn_printLokasi.setBackground(new java.awt.Color(0, 204, 204));
        btn_printLokasi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_printLokasi.setForeground(new java.awt.Color(255, 255, 255));
        btn_printLokasi.setText("Cetak");
        btn_printLokasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printLokasiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_dataLokasiLayout = new javax.swing.GroupLayout(pn_dataLokasi);
        pn_dataLokasi.setLayout(pn_dataLokasiLayout);
        pn_dataLokasiLayout.setHorizontalGroup(
            pn_dataLokasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_dataLokasiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pn_dataLokasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_dataLokasiLayout.createSequentialGroup()
                    .addGap(70, 70, 70)
                    .addComponent(btn_printLokasi, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(70, Short.MAX_VALUE)))
        );
        pn_dataLokasiLayout.setVerticalGroup(
            pn_dataLokasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_dataLokasiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(104, Short.MAX_VALUE))
            .addGroup(pn_dataLokasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_dataLokasiLayout.createSequentialGroup()
                    .addGap(50, 50, 50)
                    .addComponent(btn_printLokasi)
                    .addContainerGap(53, Short.MAX_VALUE)))
        );

        pn_dataKaryawan.setBackground(new java.awt.Color(204, 204, 255));
        pn_dataKaryawan.setPreferredSize(new java.awt.Dimension(220, 130));
        pn_dataKaryawan.setRoundBottomLeft(15);
        pn_dataKaryawan.setRoundBottomRight(15);
        pn_dataKaryawan.setRoundTopLeft(15);
        pn_dataKaryawan.setRoundTopRight(15);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Laporan Data Karyawan");

        btn_printKaryawan.setBackground(new java.awt.Color(0, 204, 204));
        btn_printKaryawan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_printKaryawan.setForeground(new java.awt.Color(255, 255, 255));
        btn_printKaryawan.setText("Cetak");
        btn_printKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printKaryawanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_dataKaryawanLayout = new javax.swing.GroupLayout(pn_dataKaryawan);
        pn_dataKaryawan.setLayout(pn_dataKaryawanLayout);
        pn_dataKaryawanLayout.setHorizontalGroup(
            pn_dataKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_dataKaryawanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pn_dataKaryawanLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(btn_printKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_dataKaryawanLayout.setVerticalGroup(
            pn_dataKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_dataKaryawanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(27, 27, 27)
                .addComponent(btn_printKaryawan)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pn_pilihLaporanLayout = new javax.swing.GroupLayout(pn_pilihLaporan);
        pn_pilihLaporan.setLayout(pn_pilihLaporanLayout);
        pn_pilihLaporanLayout.setHorizontalGroup(
            pn_pilihLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_pilihLaporanLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(pn_pilihLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                    .addComponent(cbx_laporan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pn_pilihLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(pn_dataLokasi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pn_dataBarang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pn_dataKaryawan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_pilihLaporanLayout.setVerticalGroup(
            pn_pilihLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_pilihLaporanLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addComponent(cbx_laporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(pn_pilihLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pn_dataBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn_dataLokasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn_dataKaryawan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(3, 3, 3))
        );

        pn_tampilLaporan.setBackground(new java.awt.Color(255, 255, 255));
        pn_tampilLaporan.setRoundBottomLeft(20);
        pn_tampilLaporan.setRoundBottomRight(20);
        pn_tampilLaporan.setRoundTopLeft(20);
        pn_tampilLaporan.setRoundTopRight(20);

        javax.swing.GroupLayout pn_tampilLaporanLayout = new javax.swing.GroupLayout(pn_tampilLaporan);
        pn_tampilLaporan.setLayout(pn_tampilLaporanLayout);
        pn_tampilLaporanLayout.setHorizontalGroup(
            pn_tampilLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
        pn_tampilLaporanLayout.setVerticalGroup(
            pn_tampilLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelCustom3.setBackground(new java.awt.Color(255, 255, 255));
        panelCustom3.setRoundBottomLeft(20);
        panelCustom3.setRoundBottomRight(20);
        panelCustom3.setRoundTopLeft(20);
        panelCustom3.setRoundTopRight(20);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("LAPORAN ");
        panelCustom3.add(jLabel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelCustom3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pn_pilihLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pn_tampilLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCustom3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pn_tampilLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn_pilihLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void cbx_laporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_laporanActionPerformed
        // TODO add your handling code here:
//        * Pilih Laporan *
//        Laporan Data Barang
//        Laporan Lokasi
//        Laporan Karyawan
        if(cbx_laporan.getSelectedItem()=="* Pilih Laporan *"){
            pn_dataBarang.setVisible(false);
            pn_dataKaryawan.setVisible(false);
            pn_dataLokasi.setVisible(false);
        }else if(cbx_laporan.getSelectedItem()=="Laporan Data Barang"){
            pn_dataBarang.setVisible(true);
            pn_dataKaryawan.setVisible(false);
            pn_dataLokasi.setVisible(false);
        }else if(cbx_laporan.getSelectedItem()=="Laporan Lokasi"){
            pn_dataBarang.setVisible(false);
            pn_dataKaryawan.setVisible(false);
            pn_dataLokasi.setVisible(true);
        }else if(cbx_laporan.getSelectedItem()=="Laporan Karyawan"){
            pn_dataBarang.setVisible(false);
            pn_dataKaryawan.setVisible(true);
            pn_dataLokasi.setVisible(false);
        }

    }//GEN-LAST:event_cbx_laporanActionPerformed

    private void btn_printbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printbarangActionPerformed
        // TODO add your handling code here:
        pn_tampilLaporan.removeAll();
        servis_lap.lapDataBarang(pn_tampilLaporan);
    }//GEN-LAST:event_btn_printbarangActionPerformed

    private void btn_printLokasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printLokasiActionPerformed
        // TODO add your handling code here:
        pn_tampilLaporan.removeAll();
        servis_lap.lapLokasi(pn_tampilLaporan);
    }//GEN-LAST:event_btn_printLokasiActionPerformed

    private void btn_printKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printKaryawanActionPerformed
        // TODO add your handling code here:
        pn_tampilLaporan.removeAll();
        servis_lap.lapKaryawan(pn_tampilLaporan);
    }//GEN-LAST:event_btn_printKaryawanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_printKaryawan;
    private javax.swing.JButton btn_printLokasi;
    private javax.swing.JButton btn_printbarang;
    private javax.swing.JComboBox<String> cbx_laporan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private custom.panelCustom panelCustom3;
    private custom.panelCustom pn_dataBarang;
    private custom.panelCustom pn_dataKaryawan;
    private custom.panelCustom pn_dataLokasi;
    private custom.panelCustom pn_pilihLaporan;
    private custom.panelCustom pn_tampilLaporan;
    // End of variables declaration//GEN-END:variables

}
